.github/workflows/linting-and-tests.yml
.github/workflows/release-please.yml
CLAUDE.md

This PR fixes the release-please workflow to properly authenticate with GitHub for creating releases by migrating from using a client secret directly to generating a proper GitHub App token.
- Added a new step to generate a GitHub App token using the app ID and private key
- Updated the authentication for the "Fetch GitHub release" step to use the generated token
- Updated the authentication for the tauri-action step to use the generated token instead of the client secret
Previously, the workflow was attempting to use `ARCHESTRA_RELEASER_GITHUB_APP_CLIENT_SECRET` directly as a `GITHUB_TOKEN`, which is incorrect. GitHub App client secrets are not valid authentication tokens. This change properly generates a GitHub App installation token which has the necessary permissions to create …

chore: Setup releases fro Windows and Linux

---

.github/workflows/linting-and-tests.yml
CLAUDE.md

This PR improves the readability of CI job names in the GitHub Actions UI.
- Added human-friendly `name` field to each matrix configuration in the `rust-linting-and-tests` job
- Updated the job name to use `${ matrix.name }` instead of `${ matrix.platform }`
Instead of seeing technical platform names like `ubuntu-latest` in the CI checks, we now see more readable names:
- `Rust Linting and Tests (Ubuntu)` instead of `Rust Linting and Tests (ubuntu-latest)`
- `Rust Linting and Tests (macOS (Arm))` instead of `Rust Linting and Tests (macos-latest)`
- `Rust Linting and Tests (macOS (Intel))` instead of `Rust Linting and Tests (macos-latest)`
- `Rust Linting and Tests (Windows)` instead of `Rust Linting and Tests (windows-latest)`
This makes it easier to understand which platform each CI job …

ci: update `linting-and-tests` CI job (for required GH PR checks)

---

.github/workflows/claude-code.yml
.github/workflows/claude-pull-requests.yml
.github/workflows/user-scoped-claude-code.yml
.github/workflows/user-scoped-claude-pull-requests.yml
CLAUDE.md

This PR refactors our Claude GitHub Action workflows to implement user-scoped authentication, ensuring compliance with Anthropic''s terms of service regarding OAuth token usage.
- **Before**: Single shared OAuth token (`CLAUDE_CODE_OAUTH_TOKEN`) used by all users
- **After**: Individual OAuth tokens per authorized user, preventing token sharing
1. **Converted existing workflows to reusable templates**:
- `claude-code.yml` - Now accepts OAuth token as input
- `claude-pull-requests.yml` - Now accepts OAuth token as input
2. **Added user-scoped wrapper workflows**:
- `user-scoped-claude-code.yml` - Orchestrates Claude code actions per user
- `user-scoped-claude-pull-requests.yml` - Orchestrates Claude PR actions per user
3. **Currently authorized users**:
- `joeyorlando` → …

ci: user scoped claude GH action workflows

---

desktop_app/src/backend/server/index.ts
desktop_app/src/backend/utils/fastify-logger-stream.ts

This PR unifies Fastify''s logging system with the existing application logging infrastructure by routing all Fastify logs through the centralized electron-log backend logger.
- **Added `fastify-logger-stream.ts`**: A custom write stream that intercepts Fastify''s JSON-formatted logs and routes them through the existing backend logger
- **Updated server configuration**: Modified the Fastify server initialization to use the custom logger stream instead of default console output
The implementation creates a custom write stream that:
1. Parses Fastify''s JSON log messages
2. Maps Fastify''s numeric log levels (30=info, 40=warn, 50=error) to the backend logger''s string levels
3. Preserves the full log context while routing through electron-log
This ensures all application logs (both from the …

feat: Unify fastify logs with the rest of the logs

---

desktop_app/src/ui/components/Sidebar/ChatSidebarSection/index.tsx
desktop_app/src/ui/components/Sidebar/index.tsx
desktop_app/src/ui/components/SiteHeader/index.tsx

This PR refactors the sidebar layout to improve UI organization and fix a critical context provider issue. The changes include:
- **Fixed SiteHeader context error**: Moved SiteHeader inside SidebarProvider to resolve the "useSidebar must be used within a SidebarProvider" error reported by Sentry
- **Improved sidebar structure**: Consolidated the chat sidebar section to always display at the top, removing conditional rendering based on active view
- **Enhanced chat list UI**: Added expandable chat list that shows 5 chats by default with a "Show more" button for better UX when users have many chats
- **Simplified navigation**: Removed the LLMProvidersSidebarSection component and cleaned up navigation logic
- **Moved "New Chat" button**: Relocated from chat sidebar to site header for better …

Sidebar layout

---

CLAUDE.md
README.md

This PR adds a developer quickstart section to the README.md to help developers quickly get started with the Archestra project.
- Added a new Developer Quickstart section in the README.md
- Included simple step-by-step instructions for:
- Cloning the repository
- Installing dependencies with pnpm
- Starting the application
This change improves the developer experience by providing a clear and concise starting point for new contributors to the project. Previously, developers would need to dig through documentation to find the basic setup steps.

Add quickstart

---

desktop_app/openapi/archestra/api/openapi.json
desktop_app/src/backend/models/mcpServer/index.ts
desktop_app/src/backend/sandbox/podman/container/index.ts
desktop_app/src/backend/server/plugins/oauth/providers.ts
desktop_app/src/backend/server/plugins/oauth/providers/linkedin-browser.ts
desktop_app/src/backend/server/plugins/oauth/providers/slack-browser.ts
desktop_app/src/backend/server/plugins/oauth/utils/linkedin-token-extractor.ts
desktop_app/src/ui/lib/clients/archestra/api/gen/types.gen.ts
desktop_app/src/ui/lib/clients/archestra/catalog/gen/types.gen.ts
desktop_app/src/ui/routes/connectors.tsx
mcp_server_docker_image/Dockerfile

This PR adds support for https://github.com/stickerdaniel/linkedin-mcp-server and implements support for original Docker images.I experienced an issue where the LinkedIn MCP server would sometimes fail to start due to flaky networking connectivity errors with GitHub. Currently, it would use docker if the catalog has a `server_docker` field. I didn't merge it with the main `server` to keep DXT compatibility, however, I think we should extend DXT in this case.

Add linkedin provider and run servers from original docker images

---

desktop_app/src/backend/server/plugins/oauth/index.ts
desktop_app/src/backend/server/plugins/oauth/provider-registry.ts
desktop_app/src/backend/server/plugins/oauth/providers.ts
desktop_app/src/main-browser-auth.ts

app build doesn't work when better-sqlite3 is imported in the main process, so remove database dependencies from it

fix: remove better-sqlite3 from main process bundle

---

desktop_app/src/main.ts

Added application icon support (macOS .icns, Windows .ico, PNG fallback).
Reliable icon resolution for both dev and packaged builds (with graceful PNG fallback).
Dev:
App starts, window title shows “Archestra”.
No runtime errors.
Icon loads (fallback works if primary is invalid).
Packaged (pnpm make):
Dock / taskbar shows icon and the correct app name (macOS Dock name only changes when packaged).
No new dependencies. No build config changes besides using existing `packagerConfig.icon`
Graceful fallback if icon files are missing.
/claim #273

feat: add app icon in mac OS and windows

---

desktop_app/src/ui/routes/connectors.tsx
desktop_app/src/ui/stores/connector-catalog-store.ts

reported by @JrmyDev -- if there's an issue, for whatever reason (ex. HTTP 500), loading the MCP catalog, it was leading to a flood of API calls to the MCP Catalog (whereby Vercel would basically end up (temporarily) banning folks due to "DDoS protection" 😄)

fix: catalog loading edge-case (which led to infinite API calls to the mcp catalog)

---

desktop_app/src/ui/stores/tools-store.ts

/claim #278
• Fixes bug where tool toggles in sidebar would reset to selected state after any tools update
• Preserves user's manual selection and only auto-selects all tools on first load when no selection exists
• Improves UX by maintaining user's intended tool configuration

fix: preserve user tool selection when tools update

---

CLAUDE.md
desktop_app/openapi/archestra/api/openapi.json
desktop_app/src/backend/database/schema/cloudProvider.ts
desktop_app/src/backend/models/cloudProvider/index.ts
desktop_app/src/ui/lib/clients/archestra/api/gen/types.gen.ts

Fixes #435
Removed Ollama from the Cloud Models page as it should only appear under Local Models.
- Removed 'ollama' from `SupportedCloudProviderSchema` enum
- Removed Ollama entry from `PROVIDER_REGISTRY`
- Ollama remains correctly available as Local Models

fix: remove Ollama from cloud models page

---

desktop_app/src/ui/stores/ollama-store/index.ts

This PR fixes the issue where newly downloaded Ollama models don't appear in the chat selector without a manual refresh (CMD+R or close + reopen the app).
https://www.loom.com/share/f01c7ad73cd04cdeaa432ec88920d68a
- Modified the `updateRequiredModelDownloadProgress` function to refresh models list when download completes
- Added automatic refresh of both installed models and required models status
- Included 500ms delay to ensure Ollama has registered the new model
Fixes #451

fix: auto-refresh Ollama models list after download completes

---

desktop_app/src/backend/models/chat/index.ts
desktop_app/src/ui/components/Chat/ChatInput/index.tsx
desktop_app/src/ui/routes/chat.tsx

Fixes #411
https://www.loom.com/share/0ea86450c1a94e49a285ee57d8354590
- fixes a race condition w/ displaying the green "memory panel" inconsistently after resetting the chat
- fixed bug w/ "Restart Agent" button (previously you could smash that button as much as you wanted while the AI response was still pending)
- fixed bug w/ chat title summarization; previously we were including system/"memory" messages in that prompt

fix: race condition with memory loading on chat reset

---

desktop_app/src/backend/models/cloudProvider/index.ts
desktop_app/src/backend/server/plugins/llm/index.ts
llm-proxy/package.json
llm-proxy/pnpm-lock.yaml
llm-proxy/src/index.js

This PR adds a simple implementation of a standalone LLM proxy that could run on cloud infrastructure.When archestra-llm model is selected on desktop_app, proxy receives requests, injects the Gemini API key, proxies to the Google API, streams the response back to the app, and calculates token usage.
What need to be done:
- oauth authentication
- cloudflare and etc to prevent abuse
- persisting token usage and cutoff
- ratelimits
- make sure proxy doesn't return any sensitive data like tokens, and it is not displayed in the error message
- what else?
https://github.com/archestra-ai/archestra/issues/399

feat: Add archestra-llm provider and llm-proxy service

---

desktop_app/src/ui/components/Chat/ChatInput/index.tsx
desktop_app/src/ui/components/Chat/EmptyChatState/index.tsx
desktop_app/src/ui/components/MemoryDialog/index.tsx
desktop_app/src/ui/contexts/multi-chat-manager.tsx
desktop_app/src/ui/routes/chat.tsx
desktop_app/src/ui/stores/chat-store.ts
desktop_app/src/ui/stores/memory-store.ts
desktop_app/src/ui/stores/ollama-store/index.ts

Fixes #492
This PR moves the `selectedModel` state from the ollama store to the chat store to ensure that both ollama and non-ollama models (like OpenAI models) persist their selection across app restarts.
- Moved `selectedModel` state and `setSelectedModel` action from ollama-store to chat-store
- Added localStorage persistence to chat-store using Zustand's persist middleware
- Updated all components to use `selectedModel` from chat-store instead of ollama-store
- Removed persist middleware from ollama-store as it's no longer needed

fix: Move `selectedModel` from `ollama-store` to `chat-store` for proper persistence

---

desktop_app/src/ui/components/AuthConfirmationDialog/index.tsx

This PR fixes a React hydration error in the AuthConfirmationDialog component.
The component was rendering nested `<p>` elements, which is invalid HTML and causes hydration errors:
- `DialogDescription` renders a `<p>` element
- The conditional content inside was also wrapped in `<p>` tags
- This resulted in `<p>` elements nested inside other `<p>` elements
- Replaced the inner `<p>` tags with React fragments (`<>...</>`)
- Moved the `text-sm` class to the parent `DialogDescription` component to maintain styling
This ensures valid HTML structure while preserving the same visual appearance.

chore: HTML hydration error

---

desktop_app/src/ui/components/Chat/ChatHistory/Messages/AssistantMessage.tsx
desktop_app/src/ui/components/ToolInvocation/index.tsx

Fixes #494
This PR implements the requested feature to display tool names in a nicer format in the AssistantMessage component.
- Show MCP server name and tool name in format "server - tool"
- Falls back to raw tool ID if pretty names unavailable

feat: display pretty tool names in `AssistantMessage`

---

desktop_app/src/backend/config.ts

Updates the MCP server base Docker image from a specific version tag (0.0.1) to the latest tag. This ensures the application always uses the most recent version of the base image.
- Changed Docker base image tag from 0.0.1 to latest in config.ts
- Reordered imports for better consistency

fix: use latest base image

---

CLAUDE.md
desktop_app/src/backend/config.ts

Updates the MCP server base Docker image tag from `latest` to `0.0.2`.
This change pins the base Docker image to a specific version rather than using the `latest` tag, which improves reproducibility and prevents unexpected behavior from automatic updates to the base image.
The `0.0.2` tag corresponds to the [recent release](https://github.com/archestra-ai/archestra/pull/522) that included fixes for the MCP server base Docker image configuration.

chore: bump desktop app `sandbox.baseDockerImage` tag to `0.0.2`

---

desktop_app/src/backend/config.ts
desktop_app/src/backend/models/cloudProvider/index.ts
desktop_app/src/ui/components/CloudProviderConfigDialog/index.tsx
desktop_app/src/ui/components/OnboardingWizard/index.tsx
desktop_app/src/ui/config.ts
desktop_app/src/ui/stores/user-store.ts

This PR improves the Archestra LLM OAuth authentication flow across the application by:
- Unifying the auth callback URL configuration between backend and frontend
- Fixing the CloudProviderConfigDialog to use the existing auth event subscription
- Adding automatic model refresh after successful authentication
1. **Config Unification**: Both backend (`config.ts`) and frontend (`ui/config.ts`) now use the same callback URL pattern: `archestra-ai://auth-success`
2. **CloudProviderConfigDialog Enhancement**: 
- Added auth event subscription for Archestra provider
- Auto-closes dialog on successful authentication
- Disabled API key input for Archestra provider (OAuth-based)
3. **User Store Improvements**:
- Added `authLocation` parameter to track where authentication originated
- Refreshes …

chore: polish Archestra LLM deep-linking flows in all spots

---

CLAUDE.md
desktop_app/src/backend/models/cloudProvider/index.ts

Switch Archestra's free LLM proxy from gemini-2.5-flash to gemini-2.5-pro for enhanced performance capabilities

feat: switch to gemini-2.5-pro

---

.github/release-please/release-please-config.json

This PR adds an 'Other' section to the release-please configuration to capture commits that don't match any of the defined conventional commit types. The wildcard type `*` ensures all commits are categorized in release notes.
- Added 'Other' section with wildcard type `*` to `changelog-sections` in release-please config
- Set section as hidden to avoid cluttering release notes with miscellaneous commits
This change prevents commits from being excluded from release notes if they don't follow conventional commit formats or use types not explicitly defined in the configuration.

fix: Add 'Other' section to release-please config

---

.github/release-please/release-please-config.json

This PR fixes a JSON syntax error in the release-please configuration file by removing a trailing comma after the last object in the `changelog-sections` array.
- Removed trailing comma from line 66 of `.github/release-please/release-please-config.json`
This fix ensures the release-please configuration file is valid JSON, which should prevent parsing errors when release-please processes the configuration.

fix: release-please

---

platform/CLAUDE.md
platform/backend/src/database/migrations/0001_jittery_union_jack.sql
platform/backend/src/database/migrations/meta/0001_snapshot.json
platform/backend/src/database/migrations/meta/_journal.json
platform/backend/src/database/schemas/chat.ts
platform/backend/src/models/agent.ts
platform/backend/src/models/chat.ts
platform/backend/src/routes/proxy/openai.ts
platform/backend/src/server.ts
platform/experiments/src/cli-chat.ts
platform/shared/api-client/types.gen.ts

This PR introduces the ability to use the Archestra backend without explicitly specifying agent and chat IDs, making the integration more flexible and user-friendly.
- **Database**: Added `hash_for_id` column to the chats table to support hash-based chat identification
- **Models**: 
- Added `ensureDefaultAgentExists()` method to automatically create a default agent when none is specified
- Added `createOrGetByHash()` method to find or create chats based on message content hash
- **OpenAI Proxy**: Modified to support optional `x-archestra-chat-id` header - when not provided:
- Automatically ensures a default agent exists
- Creates/retrieves chat sessions based on SHA-256 hash of the first message content
- **CLI Chat**: Updated to support optional agent ID flag (`--agent-id`) - when not …

feat: allow not specifying agent/chat id

---

platform/CLAUDE.md
platform/backend/src/database/migrations/0002_update_tool_invocation_policy_actions.sql
platform/backend/src/database/migrations/meta/0002_snapshot.json
platform/backend/src/database/migrations/meta/_journal.json
platform/backend/src/models/agent.ts
platform/backend/src/models/interaction.ts
platform/backend/src/models/tool-invocation-policy.ts
platform/backend/src/routes/proxy/openai.ts
platform/backend/src/routes/proxy/utils/tool-invocation.ts
platform/backend/src/types/autonomy-policies/tool-invocation.ts
platform/frontend/src/app/settings/page.tsx
platform/shared/api-client/types.gen.ts

This PR enhances the tool invocation policy system by introducing more granular control over tool execution in untrusted contexts. The key changes include:
- **Renamed policy actions** for clarity:
- `allow` → `allow_when_context_is_untrusted` 
- `block` → `block_always`
- **Improved security model**: When a context is tainted (contains untrusted data), tools are blocked by default unless explicitly whitelisted via an `allow_when_context_is_untrusted` policy
- **UI updates**: Updated the frontend settings page to reflect the new action names and provide clearer policy configuration
1. **Database migration**: Updates existing policy action values to new names
2. **Backend logic**: Modified the policy evaluation to implement the new security model where untrusted contexts block all tools …

feat: allow whitelisting specific tool invocations even when data is untrusted

---

platform/backend/src/routes/proxy/utils/trusted-data.ts

The backend was throwing 500 errors when processing tool results that contained plain text instead of JSON:
```
SyntaxError: Unexpected token 'C', "Contents o"... is not valid JSON
at JSON.parse (<anonymous>)
at Object.evaluatePolicies (/backend/src/routes/proxy/utils/trusted-data.ts:45:44)
```
The trusted data policy evaluator assumed all string content from tool messages was valid JSON and called `JSON.parse()` without error handling. However, tools can return plain text responses (e.g., "Contents of..." from file reading tools).
Added try-catch around `JSON.parse()` in `backend/src/routes/proxy/utils/trusted-data.ts:45`:
- Attempts to parse string content as JSON
- Falls back to using the string as-is when parsing fails
- Prevents crashes while maintaining support for both JSON and …

fix: JSON parsing error in trusted data policy evaluation on Jan.ai

---

.github/release-please/release-please-config.json
.github/workflows/build-dockerhub-image.yml
.github/workflows/on-pull-requests.yml
.github/workflows/platform-linting-and-tests.yml
.github/workflows/release-please.yml
platform/CLAUDE.md

Simplifies the Docker Hub image build workflow and adds multi-platform support.
- Removed metadata extraction and artifact attestation steps for simpler builds
- Added explicit Docker Buildx setup for multi-platform builds
- Switched to direct tag specification instead of dynamic metadata
- Added support for both linux/amd64 and linux/arm64 platforms
- Enabled GitHub Actions cache (type=gha) for faster subsequent builds
- Removed unnecessary workflow permissions (packages:write, attestations:write)
- Temporarily hardcoded platform image version to v0.0.1 (includes TODO comment to revert)
This change improves the Docker image build process by:
1. Supporting multi-architecture builds (amd64 and arm64)
2. Utilizing build caching for improved CI performance
3. Simplifying the workflow by …

fix: tweak platform dockerhub image tags
